baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Squach-Blog'
theme = 're-terminal'

pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  math = true
  [params.banner]
    dismissible = true
    text = "Check out my GitHub"
    url = "https://github.com/squach90"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  
[languages]
  [languages.en.params]
    title = "re-Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "squachBlog"
      logoHomeLink = "/"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "submenu"
    name = "Sub menus"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "subabout"
    name = "About"
    url = "/about"
    parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "subshowcase"
    name = "Showcase"
    url = "/showcase"
    parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"