name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Remplace "main" par le nom de la branche que tu utilises

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifie le code source
      - name: Checkout source code
        uses: actions/checkout@v3

      # Étape 2 : Installe Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Étape 3 : Construis le site
      - name: Build the site
        run: hugo --minify

      # Étape 4 : Déploie sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

